ZborApp/Controllers/PorukeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExcelDataReader;
using Ical.Net;
using Ical.Net.CalendarComponents;
using Ical.Net.DataTypes;
using Ical.Net.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ZborDataStandard.ViewModels;
using ZborDataStandard.ViewModels.JSONModels;
using ZborDataStandard.ViewModels.PorukeViewModels;
using ZborDataStandard.ViewModels.ZborViewModels;
using ZborApp.Services;
using ZborDataStandard.Account;
using ZborDataStandard.Model;
using Microsoft.AspNetCore.SignalR;

namespace ZborApp.Controllers
{
    [Authorize]
    public class PorukeController : Controller
    {
        private readonly ILogger<ZborController> _logger;
        private readonly ZborDatabaseContext _ctx;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        private readonly IHubContext<ChatHub> _hubContext;

        public PorukeController(ILogger<ZborController> logger, ZborDatabaseContext ctx, UserManager<ApplicationUser> userManager, IHubContext<ChatHub> hubContext)
        {
            _logger = logger;
            _ctx = ctx;
            _userManager = userManager;
            _emailSender = new EmailSender();
            _hubContext = hubContext;

        }
        public async Task<IActionResult> Index()
        {
            ViewData["id"] = TempData["id"]; 
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var korisnik = _ctx.Korisnik.Where(k => k.Id == user.Id).SingleOrDefault();
            var razg = _ctx.Razgovor.Where(r => r.KorisnikUrazgovoru.Select(kr => kr.IdKorisnik).Contains(korisnik.Id))
                .Include(r => r.KorisnikUrazgovoru).ThenInclude(kr => kr.IdKorisnikNavigation)
                .Include(r => r.Poruka).ThenInclude(p => p.IdKorisnikNavigation).OrderByDescending(r => r.DatumZadnjePoruke).ToList();
            PorukeViewModel model = new PorukeViewModel
            {
                Razgovori = razg,
                IdKorisnik = user.Id,
                Korisnici = _ctx.Korisnik.ToList()
            };
                return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Procitano([FromBody] StringModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            Guid idRazg;
            var flag = Guid.TryParse(model.Value, out idRazg);
            if (flag == false)
                return BadRequest();
            KorisnikUrazgovoru k = _ctx.KorisnikUrazgovoru.Where(k => k.IdKorisnik == user.Id && k.IdRazgovor == idRazg).SingleOrDefault();
            if (k == null)
                return NotFound();
            k.Procitano = true;
            _ctx.SaveChanges();
            var neprocitane = _ctx.Razgovor.Where(r => r.KorisnikUrazgovoru.Where(k => k.IdKorisnik == user.Id && k.Procitano == false).Count() > 0).Select(r => r.Id.GetHashCode()).ToList();
            await _hubContext.Clients.User(user.Id.ToString()).SendAsync("Neprocitane", neprocitane);
            var m = new StringModel { Value = "Ok" };
            return Ok(m);
        }
        [HttpPost]
        public async Task<IActionResult> PromjenaNaslova([FromBody] PretragaModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            Guid idRazg;
            var flag = Guid.TryParse(model.Id, out idRazg);
            if (flag == false)
                return BadRequest();
            Razgovor r = _ctx.Razgovor.Find(idRazg);
            if (r == null)
                return NotFound();
            r.Naslov = model.Tekst;
            _ctx.SaveChanges();
            var m = new StringModel { Value = "Ok" };
            return Ok(m);
        }
        [HttpGet]
        public IActionResult Poruka(Guid id)
        {
            TempData["id"] = id;
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DohvatiPoruke()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var poruke = _ctx.Razgovor.Where(r => r.KorisnikUrazgovoru.Select(k => k.IdKorisnik).Contains(user.Id)).OrderByDescending(r => r.DatumZadnjePoruke).Take(3)
                .Include(r => r.Poruka).ThenInclude(p => p.IdKorisnikNavigation)
                .Include(r => r.KorisnikUrazgovoru).ToList();
            int neprocitane = _ctx.Razgovor.Where(r => r.KorisnikUrazgovoru.Where(k => k.IdKorisnik == user.Id && k.Procitano == false).Count() > 0).Count();
            poruke.ForEach(r => r.Poruka = r.Poruka.OrderByDescending(p => p.DatumIvrijeme).ToList());
            var response = new
            {
                poruke = poruke.Select(r => new
                {
                    Id = r.Id,
                    Naziv = r.Naslov + " (" + r.Poruka.First().IdKorisnikNavigation.ImeIPrezime() + ")",
                    Datum = r.Poruka.First().DatumIvrijeme.ToString("dd.MM.yyyy. hh:mm"),
                    Slika = r.Poruka.First().IdKorisnikNavigation.IdSlika,
                    Poruka = r.Poruka.First().Poruka1,
                    Procitano = r.KorisnikUrazgovoru.Where(k => k.IdKorisnik == user.Id).SingleOrDefault().Procitano,
                }),
                Neprocitane = neprocitane

            };
            return Ok(response);
        }
        [HttpGet]
        public async Task<IActionResult> DohvatiNeprocitano()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            
            int neprocitane = _ctx.Razgovor.Where(r => r.KorisnikUrazgovoru.Where(k => k.IdKorisnik == user.Id && k.Procitano == false).Count() > 0).Count();
           
            return Ok(neprocitane);
        }
    }
}

ZborApp/Controllers/ZborController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExcelDataReader;
using Ical.Net;
using Ical.Net.CalendarComponents;
using Ical.Net.DataTypes;
using Ical.Net.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ZborDataStandard.ViewModels;
using ZborDataStandard.ViewModels.JSONModels;
using ZborDataStandard.ViewModels.ZborViewModels;
using ZborApp.Services;
using ZborDataStandard.Account;
using ZborDataStandard.Model;



namespace ZborApp.Controllers
{
    [Authorize]
    public class ZborController : Controller
    {
        private readonly ILogger<ZborController> _logger;
        private readonly ZborDatabaseContext _ctx;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        private readonly IHubContext<ChatHub> _hubContext;
        private const string LOCATION = "E:/UploadZbor/";

        public ZborController(ILogger<ZborController> logger, ZborDatabaseContext ctx, UserManager<ApplicationUser> userManager, IHubContext<ChatHub> hubContext)
        {
            _logger = logger;
            _ctx = ctx;
            _userManager = userManager;
            _emailSender = new EmailSender();
            _hubContext = hubContext;
        }
        private bool Exists(Guid idZbor)
        {
            var zbor = _ctx.Zbor.Find(idZbor);
            return zbor == null ? false : true;
        }
        private bool CheckRights(Guid idZbor, Guid idKorisnik)
        {
            var clan = _ctx.ClanZbora.Where(c => c.IdKorisnik == idKorisnik && c.IdZbor == idZbor).SingleOrDefault();
            var voditelj = _ctx.Voditelj.Where(v => v.IdZbor == idZbor).OrderByDescending(v => v.DatumPostanka).SingleOrDefault();
            if (clan != null || voditelj.IdKorisnik == idKorisnik)
                return true;
            return false;
        }
        private bool IsAdmin(Guid idZbor, Guid idKorisnik)
        {
            var zbor = _ctx.Zbor.Where(z => z.Id == idZbor).Include(z => z.Voditelj).Include(z => z.ModeratorZbora).SingleOrDefault();
            var admin = zbor.Voditelj.OrderByDescending(z => z.DatumPostanka).First();
            var mod = zbor.ModeratorZbora.Where(m => m.IdKorisnik == idKorisnik).SingleOrDefault();
            return admin.IdKorisnik == idKorisnik || mod != null ? true : false;
        }

        public async Task<IActionResult> Index()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var korisnik = _ctx.Korisnik.Where(k => k.Id == user.Id).SingleOrDefault();
            //ispravi
            var mojiZborovi = _ctx.Zbor.Where(z => z.Voditelj.Select(v => v.IdKorisnik).Contains(user.Id) || z.ClanZbora.Select(v => v.IdKorisnik).Contains(user.Id)).ToList();
            var prijaveZborovi = _ctx.Zbor.Where(z => z.PrijavaZaZbor.Select(p => p.IdKorisnik).Contains(user.Id)).Include(p => p.PrijavaZaZbor).ToList();
            var ostaliZborovi =  _ctx.Zbor.Where(z => !z.Voditelj.Select(v => v.IdKorisnik).Contains(user.Id) && !z.ClanZbora.Select(v => v.IdKorisnik).Contains(user.Id) && !z.PrijavaZaZbor.Select(p => p.IdKorisnik).Contains(user.Id) && !z.PozivZaZbor.Select(p => p.IdKorisnik).Contains(user.Id)).ToList();
            var mojiPozivi = _ctx.PozivZaZbor.Where(p => p.IdKorisnik == korisnik.Id).Include(p => p.IdZborNavigation).OrderByDescending(p => p.DatumPoziva).ToList();

            IndexViewModel model = new IndexViewModel { MojiPozivi=mojiPozivi,MojiZborovi = mojiZborovi, PoslanePrijaveZborovi = prijaveZborovi, OstaliZborovi = ostaliZborovi, KorisnikId= user.Id };
            return View(model);
        }

        [HttpGet]
        public IActionResult Dodaj()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Dodaj(DodajViewModel model)
        {
            if(ModelState.IsValid)
            {
                if(model.Novi.Naziv.Trim().Equals(""))
                {
                    ModelState.AddModelError("Naziv", "Naziv je obavezan.");
                }
                if(model.Novi.Adresa.Trim().Equals(""))
                {
                    ModelState.AddModelError("Adresa", "Adresa je obavezna");
                }
                if(!ModelState.IsValid)
                {
                    return View(model);
                }
                model.Novi.Id = Guid.NewGuid();
                ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
                Voditelj voditelj = new Voditelj
                {
                    DatumPostanka = DateTime.Now,
                    Id = Guid.NewGuid(),
                    IdZborNavigation = model.Novi,
                    IdZbor = model.Novi.Id,
                    IdKorisnik = user.Id
                };
                ClanZbora clan = new ClanZbora
                {
                    Id = Guid.NewGuid(),
                    IdKorisnik = user.Id,
                    IdZbor = model.Novi.Id,
                    DatumPridruzivanja = DateTime.Now,
                    Glas = "ne"
                };
                model.Novi.Voditelj.Add(voditelj);
                model.Novi.ClanZbora.Add(clan);
                model.Novi.ProfilZbor = new ProfilZbor();
                _ctx.Add(model.Novi);
                _ctx.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
       
     

        [HttpGet]
        public async Task<IActionResult> Profil(Guid id)
        {

            if (!Exists(id))
                return RedirectToAction("Nema", "Greska");
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            if (!CheckRights(id, user.Id))
                return RedirectToAction("Prava");
            var korisnik = _ctx.Korisnik.Find(user.Id);
            Zbor zbor = _ctx.Zbor.Where(z => z.Id == id).Include(z => z.Voditelj).Include(z => z.Projekt).SingleOrDefault();
            IEnumerable<Obavijest> obavijesti = _ctx.Obavijest.Where(o => o.IdZbor == id)
                .Include(o => o.IdKorisnikNavigation)
                .Include(o => o.LajkObavijesti)
                .Include(o => o.KomentarObavijesti).ThenInclude(k => k.LajkKomentara)
                .Include(o => o.KomentarObavijesti).ThenInclude(k => k.IdKorisnikNavigation)
                  .Include(o => o.KomentarObavijesti).OrderBy(d => d.DatumObjave)
                .OrderByDescending(O => O.DatumObjave);
            ProfilViewModel model = new ProfilViewModel { Zbor = zbor, Obavijesti = obavijesti, IdKorisnik = user.Id, ImeIPrezime = korisnik.Ime + " " + korisnik.Prezime, Slika = korisnik.IdSlika };
            var admin = zbor.Voditelj.OrderByDescending(z => z.DatumPostanka).First();
            model.Admin = IsAdmin(id, user.Id);
            model.Projekti = zbor.Projekt.Where(p => !p.Zavrsen).ToList();
            ViewData["zborId"] = id;
            ViewData["zborIme"] = zbor.Naziv;
            ViewData["idSlika"] = zbor.IdSlika;
            ViewData["Model"] = TempData["Model"];
            return View(model);
        }

       

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Profil(Guid id, ProfilViewModel model)
        {
            if (!Exists(id))
                return RedirectToAction("Nema", "Greska");
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            if (!CheckRights(id, user.Id))
                return RedirectToAction("Prava");
            if (ModelState.IsValid)
            {
                if (model.NovaObavijest.Naslov.Trim().Equals(""))
                {
                    ModelState.AddModelError("Naslov", "Naslov je obavezan.");
                }
                if (model.NovaObavijest.Tekst.Trim().Equals(""))
                {
                    ModelState.AddModelError("Adresa", "Tekst je obavezan");
                }
                if (!ModelState.IsValid)
                {
                    TempData["Model"] = "Ispravite greške unutar polja forme.";
                    return RedirectToAction("Profil", new { id = id });
                }


                model.Zbor = _ctx.Zbor.Find(id);
                model.NovaObavijest.DatumObjave = DateTime.Now;
                model.NovaObavijest.Id = Guid.NewGuid();
                model.NovaObavijest.IdZbor = id;
                model.NovaObavijest.IdKorisnik = user.Id;

                var pretplatnici = _ctx.PretplataNaZbor.Where(p => p.IdZbor == id && p.Obavijesti).Select(p => p.IdKorisnik).ToHashSet();

                if (model.OdabraniProjekti != null)
                {
                    var projekti = model.OdabraniProjekti.Split(",");
                    foreach(var projektId in projekti)
                    {
                        var idProj = Guid.Parse(projektId);
                        var pro = _ctx.Projekt.Find(idProj);
                        if(pro == null || pro.IdZbor != id)
                        {
                            continue;
                        }
                        var ob = new ObavijestVezanaUzProjekt
                        {
                            Id = Guid.NewGuid(),
                            IdProjekt = Guid.Parse(projektId),
                            IdObavijest = model.NovaObavijest.Id
                        };
                        model.NovaObavijest.ObavijestVezanaUzProjekt.Add(ob);
                        pretplatnici.Add(_ctx.PretplataNaProjekt.Where(p => p.IdProjekt == idProj && p.Obavijesti).Select(p => p.IdKorisnik).SingleOrDefault());

ZborApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zboris</title>
    <link rel="stylesheet" href="~/css/sb-admin-2.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
</head>

<body>
    <style>
        body {
            font-family: 'Montserrat', sans-serif;
        }
    </style>

    <body id="page-top">

        <!-- Page Wrapper -->
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a asp-area="" asp-controller="Zbor" asp-action="Index" class="sidebar-brand d-flex align-items-center justify-content-center" style=" background-image: url(/logo.png); background-size:inherit; background-repeat: no-repeat;">
                </a>
                <!--Tu ide jos nekaj ako je odabran zbor. to ćemp napraviti.-->
                @await Html.PartialAsync("_ZborNavigacijaPartial")
            </ul>

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    <!-- Topbar -->
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                        <!-- Sidebar Toggle (Topbar) -->
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>

                        <!-- Topbar Search -->
                        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" asp-action="Pretraga" asp-controller="Zbor">
                            <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small" placeholder="Pretraži" aria-label="Search" aria-describedby="basic-addon2" value="" name="upit">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>

                        <!-- Topbar Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Nav Item - Alerts -->
                            <li class="nav-item dropdown no-arrow mx-1">
                                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="procitaj3Obavijesti()">
                                    <i class="fa fa-bell"></i>
                                    <!-- Counter - Alerts -->
                                    <span id="notificationCounter" class="badge badge-danger badge-counter"></span>
                                </a>
                                <!-- Dropdown - Alerts -->
                                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown" >
                                    <h6 class="dropdown-header">
                                        Obavijesti
                                    </h6>
                                    <div id="obavijesti_layout">

                                    </div>



                                    <a class="dropdown-item text-center small text-gray-500" asp-action="Obavijesti" asp-controller="Korisnik">Više obavijesti</a>
                                </div>
                            </li>

                            <!-- Nav Item - Messages -->
                            <li class="nav-item dropdown no-arrow mx-1">
                                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <!-- Counter - Messages -->
                                    <span id="messageCounter" class="badge badge-danger badge-counter"></span>
                                </a>
                                <!-- Dropdown - Messages -->
                                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                                    <h6 class="dropdown-header">
                                        Poruke
                                    </h6>
                                    <div id="poruke_layout">

                                    </div>



                                    <a class="dropdown-item text-center small text-gray-500" asp-action="Index" asp-controller="Poruke">Više poruka</a>
                                </div>
                            </li>

                            <div class="topbar-divider d-none d-sm-block"></div>

                            @await Html.PartialAsync("_LoginPartial")

                        </ul>

                    </nav>
                    <div class="container-fluid">




                        <main role="main" class="pb-3">
                            @RenderBody()
                            <div class="modal fade" id="napustanjeZbora" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Napuštanje zbora</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Jeste li sigurni da želite napustiti zbor?</p>
                                            <p id="idNapusti" style="display:none"></p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" onclick="napustiZbor()">Da</button>
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Ne</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </main>
                    </div>
                </div>
            </div>
        </div>
    </body>


    <footer class="border-top footer text-muted">
        <div class="container" style="margin-left:0px; padding-left:20px">
            &copy; 2020 - Zboris - Diplomski rad FER
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>

    <script src="~/js/chat_layout.js"></script>
    <script>
       
    </script>
    <script>renderChat(); renderNot()</script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ZborApp/Views/Shared/_PorukePartial.cshtml
@using Microsoft.AspNetCore.Identity
@using ZborDataStandard.ViewModels
@using ZborDataStandard.Account

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject ZborDataStandard.Model.ZborDatabaseContext ctx


@section Scripts{
    
}

ZborApp/Views/Shared/_ZborNavigacijaPartial.cshtml
@using ZborDataStandard.Account
@using Microsoft.AspNetCore.Identity
@using ZborDataStandard.ViewModels

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject ZborDataStandard.Model.ZborDatabaseContext ctx

@{
    var zborId = ViewData["zborId"];
    var zborIme = ViewData["zborIme"];
    var idSlika = ViewData["idSlika"];
}


@if (zborId != null)
{
    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link text-center" asp-controller="Zbor" asp-action="Profil" asp-route-id="@zborId">
            <img src="/Repozitorij/GetZbor/@idSlika" alt="profpic" class="img-profile rounded-circle" style="width:40px; height:40px; background-color:white"><br />

            <span>@zborIme</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
   
    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" asp-controller="Zbor" asp-action="Profil" asp-route-id="@zborId">
            <i class="fa fa-folder-o"></i>
            <span>Obavijesti</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Zbor" asp-action="Pitanja" asp-route-id="@zborId">
            <i class="fa fa-question-circle"></i>
            <span>Pitanja</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Zbor" asp-action="Kalendar" asp-route-id="@zborId">
            <i class="fa fa-calendar"></i>
            <span>Kalendar</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Zbor" asp-action="Projekti" asp-route-id="@zborId">
            <i class="fa fa-tasks"></i>
            <span>Projekti</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Repozitorij" asp-action="Zbor" asp-route-id="@zborId">
            <i class="fa fa-file-o"></i>
            <span>Repozitorij</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Zbor" asp-action="JavniProfil" asp-route-id="@zborId">
            <i class="fa fa-magic"></i>
            <span>Javni profil</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Administracija
    </div>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Zbor" asp-action="Pretplate" asp-route-id="@zborId">
            <i class="fa fa-sticky-note"></i>
            <span>Pretplate</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Zbor" asp-action="Administracija" asp-route-id="@zborId">
            <i class="fa fa-cog"></i>
            <span>Upravljanje zborom</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <li class="nav-item">
        <a class="nav-link hoverable" data-toggle="modal" data-target="#napustanjeZbora" data-id="@zborId">
            <i class="fa fa-arrow-circle-o-down"></i>
            <span>Napusti zbor</span>
        </a>
    </li>




}
else if (SignInManager.IsSignedIn(User))
{
    <hr class="sidebar-divider my-0" />
    var kor = ctx.Korisnik.Where(k => k.Id == Guid.Parse(UserManager.GetUserId(User))).SingleOrDefault();

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link text-center" asp-controller="Zbor" asp-action="Index">
            <img src="/Repozitorij/Get/@kor.IdSlika" alt="profpic" class="img-profile rounded-circle" style="width:40px; height:40px;"><br />
            <span>@kor.ImeIPrezime()</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" asp-controller="Poruke" asp-action="Index">
            <i class="fa fa-envelope-o"></i>
            <span>Poruke</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Korisnik" asp-action="Obavijesti">
            <i class="fa fa-bell"></i>
            <span>Obavijesti</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Repozitorij" asp-action="Korisnik" asp-route-id="@kor.Id">
            <i class="fa fa-file-o"></i>
            <span>Repozitorij</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Forum" asp-action="Index">
            <i class="fa fa-comments-o"></i>
            <span>Forum</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Korisnik" asp-action="JavniProfil" asp-route-id="@kor.Id">
            <i class="fa fa-magic"></i>
            <span>Javni profil</span>
        </a>
    </li>
}