ZborApp/Models/NoviDogadjajViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZborDataStandard.Model;

namespace ZborDataStandard.ViewModels.ZborViewModels
{
    public class NoviDogadjajViewModel
    {
        public Guid IdProjekt { get; set; }
        public Dogadjaj Novi { get; set; }
        public List<SelectListItem> VrsteDogadjaja { get; set; }


    }
}

ZborApp/Models/ProjektiViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ZborDataStandard.Model;

namespace ZborDataStandard.ViewModels.ZborViewModels
{
    public class ProjektiViewModel
    {
        public Projekt Novi { get; set; }
        public Guid IdZbor { get; set; }
        public Guid IdKorisnik { get; set; }
        public bool Admin { get; set; }

        public IEnumerable<Projekt> Projekti { get; set; }
        public IEnumerable<Projekt> MojiProjekti { get; set; }

        public IEnumerable<Projekt> PrijavaProjekti { get; set; }
        public IEnumerable<Projekt> OstaliProjekti { get; set; }
        public IEnumerable<Projekt> ZavrseniProjekti { get; set; }


        public List<SelectListItem> VrstePodjele { get; set; }  

    }
}

ZborApp/Controllers/KorisnikController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExcelDataReader;
using Ical.Net;
using Ical.Net.CalendarComponents;
using Ical.Net.DataTypes;
using Ical.Net.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ZborDataStandard.ViewModels;
using ZborDataStandard.ViewModels.JSONModels;
using ZborDataStandard.ViewModels.ForumViewModels;
using ZborApp.Services;
using ZborDataStandard.Account;
using ZborDataStandard.Model;
using ZborDataStandard.ViewModels.KorisnikVIewModels;

namespace ZborApp.Controllers
{
    [Authorize]
    public class KorisnikController : Controller
    {
        private readonly AppSettings appData = new AppSettings();

        private readonly ILogger<KorisnikController> _logger;
        private readonly ZborDatabaseContext _ctx;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        public KorisnikController(ILogger<KorisnikController> logger, ZborDatabaseContext ctx, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _ctx = ctx;
            _userManager = userManager;
            _emailSender = new EmailSender();
        }
       
        [HttpGet]
        public async Task<IActionResult> Index(Guid id)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var korisnik = _ctx.Korisnik.Where(k => k.Id == id).Include(k => k.ClanZbora).ThenInclude(c => c.IdZborNavigation).SingleOrDefault();
            if (korisnik == null)
                return RedirectToAction("Nema", "Greska");
            
            JavniProfilViewModel model = new JavniProfilViewModel
            {
                Korisnik = korisnik,
                Aktivni = user.Id
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Uredi([FromBody] PretragaModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            _ctx.Korisnik.Find(user.Id).Opis = model.Tekst;
            _ctx.SaveChanges();
            return Ok();
        }
        [AllowAnonymous]
        public async Task<IActionResult> Galerija(Guid id)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var korisnik = _ctx.Korisnik.Find(id);
            if (korisnik == null)
                return RedirectToAction("Nema", "Greska");
            var slike = _ctx.RepozitorijKorisnik.Where(z => z.IdKorisnik == id).ToList().Where(s => s.JeSlika()).ToList();
            if(user==null || user.Id != id)
            {
                slike = slike.Where(s => s.Privatno == false).ToList();
            }
            GalerijaViewModel model = new GalerijaViewModel
            {
                Slike = slike,
                Clan = user!=null && user.Id == id,
                IdKorisnik = id
            };
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> DohvatiObavijesti()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var poruke = _ctx.OsobneObavijesti.Where(r => r.IdKorisnik == user.Id).OrderByDescending(r => r.Datum).Take(3).ToList();
            int neprocitane = _ctx.OsobneObavijesti.Where(r => r.IdKorisnik == user.Id && r.Procitano == false).Count();
            var response = new
            {
                poruke = poruke,
                Neprocitane = neprocitane

            };
            return Ok(response);
        }
        [HttpGet]
        public async Task<IActionResult> DohvatiNeprocitano()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);

            int neprocitane = _ctx.OsobneObavijesti.Where(r => r.IdKorisnik == user.Id && r.Procitano == false).Count();

            return Ok(neprocitane);
        }
        [HttpPost]
        public async Task<IActionResult> ProcitajVrh()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var poruke = _ctx.OsobneObavijesti.Where(r => r.IdKorisnik == user.Id).OrderByDescending(r => r.Datum).Take(3).ToList();
            foreach (var o in poruke)
                o.Procitano = true;
            _ctx.SaveChanges();
            int neprocitane = _ctx.OsobneObavijesti.Where(r => r.IdKorisnik == user.Id && r.Procitano == false).Count();

            return Ok(neprocitane);
        }
        [HttpGet]
        public async Task<IActionResult> Obavijesti()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var model = new ObavijestiViewModel { Obavijesti = _ctx.OsobneObavijesti.Where(r => r.IdKorisnik == user.Id).OrderByDescending(r => r.Datum).AsNoTracking().ToList() };
            await _ctx.OsobneObavijesti.Where(o => o.IdKorisnik == user.Id && o.Procitano == false).ForEachAsync(o => o.Procitano = true);
            _ctx.SaveChanges();

            return View(model);
        }
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> JavniProfil(Guid id)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var korisnik = _ctx.Korisnik.Where(k => k.Id == id).Include(k => k.ClanZbora).ThenInclude(c => c.IdZborNavigation).SingleOrDefault();
            if (korisnik == null)
                return RedirectToAction("Nema", "Greska");

            JavniProfilViewModel model = new JavniProfilViewModel
            {
                Korisnik = korisnik,
                Aktivni = user==null?Guid.Empty:user.Id 
            };
            
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Urediomeni([FromBody] PretragaModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            _ctx.Korisnik.Find(user.Id).Opis = model.Tekst;
            _ctx.SaveChanges();
            return Ok();
        }
    }
}

ZborApp/Controllers/RepozitorijController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExcelDataReader;
using Ical.Net;
using Ical.Net.CalendarComponents;
using Ical.Net.DataTypes;
using Ical.Net.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ZborDataStandard.ViewModels;
using ZborDataStandard.ViewModels.JSONModels;
using ZborDataStandard.ViewModels.PorukeViewModels;
using ZborDataStandard.ViewModels.RepozitorijViewModels;
using ZborDataStandard.ViewModels.ZborViewModels;
using ZborApp.Services;
using ZborDataStandard.Account;
using ZborDataStandard.Model;



namespace ZborApp.Controllers
{
    [Authorize]
    public class RepozitorijController : Controller
    {
        private const string LOCATION = "E:/UploadZbor/";
        private const string LOCATION_CHOIR = "E:/UploadZbor/Zbor/";

        private readonly ILogger<RepozitorijController> _logger;
        private readonly ZborDatabaseContext _ctx;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHubContext<ChatHub> _hubContext;

        public RepozitorijController(ILogger<RepozitorijController> logger, ZborDatabaseContext ctx, UserManager<ApplicationUser> userManager, IHubContext<ChatHub> hubContext)
        {
            _logger = logger;
            _ctx = ctx;
            _userManager = userManager;
            _hubContext = hubContext;
        }
        private bool Exists(Guid idZbor)
        {
            var zbor = _ctx.Zbor.Find(idZbor);
            return zbor == null ? false : true;
        }
        private bool CheckRights(Guid idZbor, Guid idKorisnik)
        {
            var clan = _ctx.ClanZbora.Where(c => c.IdKorisnik == idKorisnik && c.IdZbor == idZbor).SingleOrDefault();
            var voditelj = _ctx.Voditelj.Where(v => v.IdZbor == idZbor).OrderByDescending(v => v.DatumPostanka).SingleOrDefault();
            if (clan != null || voditelj.IdKorisnik == idKorisnik)
                return true;
            return false;
        }
        private bool IsAdmin(Guid idZbor, Guid idKorisnik)
        {
            var zbor = _ctx.Zbor.Where(z => z.Id == idZbor).Include(z => z.Voditelj).Include(z => z.ModeratorZbora).SingleOrDefault();
            var admin = zbor.Voditelj.OrderByDescending(z => z.DatumPostanka).First();
            var mod = zbor.ModeratorZbora.Where(m => m.IdKorisnik == idKorisnik).SingleOrDefault();
            return admin.IdKorisnik == idKorisnik || mod != null ? true : false;
        }
        public async Task<IActionResult> Korisnik(Guid id)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var korisnik = _ctx.Korisnik.Where(k => k.Id == user.Id).SingleOrDefault();
            var datoteke = _ctx.RepozitorijKorisnik.Where(r => r.IdKorisnik == id).OrderByDescending(r => r.DatumPostavljanja).ToList();
            if (id != korisnik.Id)
                datoteke = datoteke.Where(d => d.Privatno == false).ToList();
            
            RepozitorijViewModel model = new RepozitorijViewModel
            {
                Datoteke = datoteke, 
                IdKorisnik = user.Id,
                IdTrazeni = id
            };
            return View(model);
        }
        public async Task<IActionResult> Zbor(Guid id)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var korisnik = _ctx.Korisnik.Where(k => k.Id == user.Id).SingleOrDefault();
            var datoteke = _ctx.RepozitorijZbor.Where(r => r.IdZbor == id).Include(k => k.IdKorisnikNavigation).OrderByDescending(r => r.DatumPostavljanja).ToList();
            if (!_ctx.ClanZbora.Where(c => c.IdZbor == id).Select(c => c.IdKorisnik).Contains(user.Id))
                datoteke = datoteke.Where(d => d.Privatno == false).ToList();

            var zbor = _ctx.Zbor.Where(z => z.Id == id).Include(z => z.Voditelj).Include(z => z.ModeratorZbora).SingleOrDefault();
            var admin = zbor.Voditelj.OrderByDescending(z => z.DatumPostanka).First();
            var mod = zbor.ModeratorZbora.Where(m => m.IdKorisnik == user.Id).SingleOrDefault();
            bool flagAdmin  =  admin.IdKorisnik == user.Id || mod != null ? true : false;
            var clan = _ctx.ClanZbora.Where(c => c.IdKorisnik == user.Id && c.IdZbor == id).SingleOrDefault();
            bool flagClan = clan == null ? false : true;
            RepozitorijZborViewModel model = new RepozitorijZborViewModel
            {
                Datoteke = datoteke,
                IdKorisnik = user.Id,
                IdTrazeni = id,
                IdZbor = id,
                Promjena = flagAdmin,
                Clan = flagClan
            };
            ViewData["zborId"] = id;
            ViewData["zborIme"] = zbor.Naziv;
            ViewData["idSlika"] = zbor.IdSlika;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Objavi([FromBody] StringModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            Guid idRep;
            var flag = Guid.TryParse(model.Value, out idRep);
            if (flag == false)
                return BadRequest();
            //provjera usera bla bla
            var d = _ctx.RepozitorijKorisnik.Find(idRep);
            if (d == null)
                return NotFound();
            if (d.IdKorisnik != user.Id)
                return Forbid();
            d.Privatno = false;
            _ctx.SaveChanges();
            var m = new StringModel { Value = "Ok" };
            return Ok(m);
        }
        [HttpPost]
        public async Task<IActionResult> ObjaviZbor([FromBody] StringModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            Guid idRep;
            var flag = Guid.TryParse(model.Value, out idRep);
            if (flag == false)
                return BadRequest();
            var d = _ctx.RepozitorijZbor.Find(idRep);
            if (d == null)
                return NotFound();
            if (!IsAdmin(d.IdZbor, user.Id) && d.IdKorisnik != user.Id)
                return Forbid();
            d.Privatno = false;
            _ctx.SaveChanges();
            var m = new StringModel { Value = "Ok" };
            return Ok(m);
        }
        [HttpPost]
        public async Task<IActionResult> Privatiziraj([FromBody] StringModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            Guid idRep;
            var flag = Guid.TryParse(model.Value, out idRep);
            if (flag == false)
                return BadRequest();
            //provjera usera bla bla
            var d = _ctx.RepozitorijKorisnik.Find(idRep);
            if (d == null)
                return NotFound();
            if (d.IdKorisnik != user.Id)
                return Forbid();
            d.Privatno = true;
            _ctx.SaveChanges();
            var m = new StringModel { Value = "Ok" };
            return Ok(m);
        }
        [HttpPost]
        public async Task<IActionResult> PrivatizirajZbor([FromBody] StringModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            Guid idRep;
            var flag = Guid.TryParse(model.Value, out idRep);
            if (flag == false)
                return BadRequest();
            var d = _ctx.RepozitorijZbor.Find(idRep);
            if (d == null)
                return NotFound();
            if (!IsAdmin(d.IdZbor, user.Id) && d.IdKorisnik != user.Id)
                return Forbid();
            d.Privatno = true;
            _ctx.SaveChanges();
            var m = new StringModel { Value = "Ok" };
            return Ok(m);
        }
        [HttpPost]
        public async Task<IActionResult> PromjenaNaziva([FromBody] PretragaModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            Guid idRep;
            var flag = Guid.TryParse(model.Id, out idRep);
            if (flag == false)
                return BadRequest();
            var d = _ctx.RepozitorijKorisnik.Find(idRep);
            if (d == null)
                return NotFound();
            if (d.IdKorisnik != user.Id)
                return Forbid();
            d.Naziv = model.Tekst.Trim() + "." + d.GetEkstenzija();
            _ctx.SaveChanges();
            var m = new StringModel { Value = "Ok" };
            return Ok(m);
        }
        [HttpPost]
        public async Task<IActionResult> PromjenaNazivaZbor([FromBody] PretragaModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            Guid idRep;
            var flag = Guid.TryParse(model.Id, out idRep);
            if (flag == false)
                return BadRequest();
            var d = _ctx.RepozitorijZbor.Find(idRep);
            if (d == null)
                return NotFound();
            if (!IsAdmin(d.IdZbor, user.Id) && d.IdKorisnik != user.Id)
                return Forbid();
            d.Naziv = model.Tekst.Trim() + "." + d.GetEkstenzija();
            _ctx.SaveChanges();
            var m = new StringModel { Value = "Ok" };
            return Ok(m);
        }
        public async Task<IActionResult> Upload(RepozitorijViewModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var files = model.FormFiles;
            long size = files.Sum(f => f.Length);

            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {

ZborApp/Views/Zbor/Galerija.cshtml
@model ZborDataStandard.ViewModels.ZborViewModels.GalerijaViewModel
@{
    ViewData["Title"] = "Galerija";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet"/>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Galerija</h1>
    </div>
    @if(Model.Clan)
    {
        <div>
            <a asp-action="Zbor" asp-controller="Repozitorij" asp-route-id="@Model.IdZbor">Dodavanje i brisanje slika</a>
        </div>
    }
    <div class="row justify-content-center">

        <div class="col-md-8">
            <div class="row">
                @foreach (var slika in Model.Slike)
                {
                    <a href="/Repozitorij/GetZbor/@slika.Id" data-toggle="lightbox" data-gallery="example-gallery" class="col-4" data-type="image" data-title="@slika.Naziv" @if (Model.Clan) { <text>data-footer = "<a href=/Repozitorij/PromjenaProfilneZbor/@slika.Id>Postavi kao profilnui sliku</a>"</text>}>

<img src="/Repozitorij/GetZbor/@slika.Id" class="img-fluid">
                    </a>
                }
            </div>
        </div>
    </div>

@section Scripts{ 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
    <script>
        $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                event.preventDefault();
                $(this).ekkoLightbox();
            });
    </script>
}

ZborApp/Views/Zbor/Index.cshtml
@using ZborDataStandard.Model;
@model ZborDataStandard.ViewModels.ZborViewModels.IndexViewModel
@{
    ViewData["Title"] = "Zborovi";
}
    <div class="">

            <h1 class="h3 mb-0 text-gray-800">Moji zborovi</h1>
        <br/
            <h4><a asp-action="Dodaj">+ Dodaj vlastiti zbor</a></h4>

    </div>

    <div class="row">
        <div class="col-6">
            <div class="col-12">

                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Moji zborovi</h6>
                       
                    </div>
                    <!-- Card Body -->
                    <div class="card-body">
                        <div class="card-text">
                            @if (Model.MojiZborovi == null || Model.MojiZborovi.Count() == 0)
                            {
                                <p>Učlanite se u neki zbor!</p>
                            }
                            @foreach (Zbor zbor in Model.MojiZborovi)
                            {
                                <div class="row" style="align-items:center; margin-bottom:5px">
                                    <div class="col-md-12">
                                        <img src="/Repozitorij/GetZbor/@zbor.IdSlika" alt="profpic" class="img-profile rounded-circle" style="width:40px; height:40px;"> &nbsp;

                                        <a asp-action="Profil" asp-route-id="@zbor.Id">@zbor.Naziv</a>
                                    </div>

                                </div>

                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            @if (Model.MojiPozivi != null && Model.MojiPozivi.Count() > 0)
            {
                <div class="col-12">

                    <div class="card shadow mb-4">
                        <!-- Card Header - Dropdown -->
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Pozivi za zbor</h6>
                        </div>
                        <!-- Card Body -->
                        <div class="card-body">
                            <div class="card-text">

                                @foreach (PozivZaZbor poziv in Model.MojiPozivi)
                                {
                                    <div class="row">
                                        <div class="col-md-8">
                                            <img src="/Repozitorij/GetZbor/@poziv.IdZborNavigation.IdSlika" alt="profpic" class="img-profile rounded-circle" style="width:40px; height:40px;"> &nbsp;
                                            <a asp-action="JavniProfil" asp-route-id="@poziv.IdZborNavigation.Id">@poziv.IdZborNavigation.Naziv</a>
                                        </div>
                                        <div class="col-md-4">
                                            <a class="btn btn-sm btn-outline-success" asp-action="PrihvatiPoziv" asp-route-id="@poziv.Id">Prihvati</a>
                                            <a class="btn btn-sm btn-outline-danger" asp-action="OdbijPoziv" asp-route-id="@poziv.Id">Odbij</a>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="col-12">

                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Zborovi u koje ste se prijavili</h6>
                    </div>
                    <!-- Card Body -->
                    <div class="card-body">
                        <div class="card-text">

                            @if (Model.PoslanePrijaveZborovi == null || Model.PoslanePrijaveZborovi.Count() == 0)
                            {
                                <p>Nema prijavljenih zborova</p>
                            }
                            @foreach (Zbor zbor in Model.PoslanePrijaveZborovi)
                            {
                                <div class="row" style="align-items:center">
                                    <div class="col-md-9" >
                                        <img src="/Repozitorij/GetZbor/@zbor.IdSlika" alt="profpic" class="img-profile rounded-circle" style="width:40px; height:40px;"> &nbsp;
                                        <a asp-action="JavniProfil" asp-route-id="@zbor.Id">@zbor.Naziv</a>
                                    </div>
                                    <div class="col-md-3" id="B-@zbor.Id">
                                        <button type="button" class="btn btn-sm btn-outline-danger" onclick="odbij('@zbor.PrijavaZaZbor.Where(p => p.IdKorisnik == Model.KorisnikId && p.IdZbor==zbor.Id).Single().Id', '@zbor.Id')">Povuci prijavu</button>
                                    </div>
                                    <div class="col-md-3" id="T-@zbor.Id" style="display: none">
                                        <text class="text-danger">Prijava obrisana.</text>

                                    </div>
                                </div>
                                <br />

                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>



@section Scripts {
    
    <script>
        function odbij(id, idZb) {
            data = { Value: id + '' }
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json;charset=utf-8",
                url: '@Url.Action("OdbijPrijavu", "Zbor")',
                data: JSON.stringify(data),
                xhrFields: {
                    withCredentials: true
                }
            }).done(function (response) {
                testB = '#B-' + idZb
                testC = '#T-' + idZb
                $(testB).hide();
                $(testC).show("slow");

            })
            .always(function () {
                g = 2;
            });

        }


    </script>

}

ZborApp/Views/Zbor/Prava.cshtml
@using ZborDataStandard.Model;
@{
    ViewData["Title"] = "Dodaj projekt";
}

<h1>Prava</h1>

<p>Nemate dovoljnu razinu prava za pristup ovoj stranici. Pristup može biti samo za članove zbora ili samo za voditelja zbora.</p>

ZborApp/Views/Zbor/Pretraga.cshtml
@model ZborDataStandard.ViewModels.ZborViewModels.PretragaViewModel;
@using ZborDataStandard.Model
@{
    ViewData["Title"] = "Pretraga";
}


<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <div class="row">
        <h1 class="h3 mb-0 text-gray-800">Pretraga</h1>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <!-- Area Chart -->
        <div class="col-12">

            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Zborovi</h6>
                  
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    @foreach(var zbor in Model.Zborovi)
                    {
                        <div class="row" style="align-items:center; margin-bottom:5px">
                            <div>
                                <img src="/Repozitorij/GetZbor/@zbor.IdSlika" alt="profpic" class="img-profile rounded-circle" style="width:40px; height:40px;"> &nbsp;

                            </div>
                            <div>
                                <a asp-action="JavniProfil" asp-controller="Zbor" asp-route-id="@zbor.Id">@zbor.Naziv</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-6">
        <!-- Area Chart -->
        <div class="col-12">

            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Korisnici</h6>

                </div>
                <!-- Card Body -->
                <div class="card-body">
                    @foreach (var kor in Model.Korisnici)
                    {
                        <div class="row" style="align-items:center; margin-bottom:5px">
                            <div>
                                <img src="/Repozitorij/Get/@kor.IdSlika" alt="profpic" class="img-profile rounded-circle" style="width:40px; height:40px;"> &nbsp;

                            </div>
                            <div>
                                <a asp-action="JavniProfil" asp-controller="Korisnik" asp-route-id="@kor.Id">@kor.ImeIPrezime()</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>